#!/bin/bash

MAX_ATTEMPTS=100
DELAY_BETWEEN_ATTEMPTS=1

while [ "$MAX_ATTEMPTS" -gt "0" ]
do
    if [ -e /var/run/netopeer2-server.sock ] || [ -e /tmp/netopeer2-server.sock ]
    then
        echo "Netopeer2-server is started"
        exec /usr/bin/test-service
    fi
    echo "Netopeer2-server has not started. Waiting"
    sleep $DELAY_BETWEEN_ATTEMPTS
    MAX_ATTEMPTS=$(($MAX_ATTEMPTS - 1))
done

echo "Netopeer2-server did not start"
exit 1
